name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: List build outputs
        run: ls -l target

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 3.17.29.202
          username: ubuntu
          key_path: cointrack-keys.pem
          source: |
            Dockerfile
            target/*.jar
          target: "/home/ubuntu/cointrack"

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: 3.17.29.202
          username: ubuntu
          key_path: cointrack-keys.pem
          script: |
            cd /home/ubuntu/cointrack
            ls -l
            JAR_NAME=$(ls target/*.jar | head -n 1)
            echo "Using JAR: $JAR_NAME"
            docker stop cointrack || true
            docker rm cointrack || true
            docker build -t cointrack .
            docker run -d --name cointrack -p 8080:8080 cointrack