name: Deploy CoinTrack to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build jar with Maven
        run: mvn clean package -DskipTests

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "target/CoinTrack-0.0.1-SNAPSHOT.jar,Dockerfile"
          target: "C:/Users/Administrator/cointrack/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd C:/Users/Administrator/cointrack
            docker rm -f cointrack || echo "no container to remove"
            docker rmi cointrack || echo "no image to remove"
            docker build -t cointrack .
            docker run -d -p 8080:8080 --name cointrack cointrack