name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Save SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > cointrack-key.pem
        chmod 600 cointrack-key.pem

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 3.17.29.202
        username: ubuntu
        key_path: cointrack-key.pem
        source: |
          Dockerfile
          target/CoinTrack-0.0.1-SNAPSHOT.jar
        target: "/home/ubuntu/cointrack"

    - name: Run Docker on EC2
      uses: appleboy/ssh-action@master
      with:
        host: 3.17.29.202
        username: ubuntu
        key_path: cointrack-key.pem
        script: |
          cd ~/cointrack
          docker build -t cointrack .
          docker stop cointrack || true
          docker rm cointrack || true
          docker run -d --name cointrack -p 80:8080 cointrack